# docker-compose.production.yml

    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: karpushind/taski_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
  frontend:
    image: karpushind/taski_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: karpushind/taski_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - 8000:80